### ISSUE TITLE
Inheritance behaviour

### ISSUE THREAD

**Issue by benebrice** [flippercloud/flipper#757]
When there is inheritance, ancestors are not verified. 

```ruby
class MyEngine::User < User
end
```
If `User;1` is allowed; `MyEngine::User,1` is not. It is a normal behaviour or should we add this as a new feature? 

This is an issue without really being one. 🤷🏻‍♂️ 

Only work around found is to define a group an check manually the inheritance before calling `Flipper.enable?` with older existing parent in the app.

**Comment by bkeepers** [comment]
Hey @benebrice, thanks for bringing this up. This is currently by (lack of) design, but I've open #758 to make this behave as expected.

While you are waiting for that to merge, you can just define your own `#flipper_id` method on `User` or even `ApplicationRecord` to use the base class to identify the actors:

```ruby
class ApplicationRecord < ActiveRecord::Base
  def flipper_id
    "#{self.class.base_class.name};#{id}"
  end
end
```

Now `MyEngine::User#flipper_id` should return the same value as `User#flipper_id`.

**Comment by benebrice** [comment]
Thanks @bkeepers !
I was trying to find a work around with groups but behaviour was not at all as expected. You solution is way better. Thanks!
