### ISSUE TITLE
Support for OpenFeature SDK Provider

### ISSUE THREAD

**Issue by kiliczsh** [flippercloud/flipper#765]
There is Ruby SDK for no provider: https://github.com/open-feature/ruby-sdk/tree/main/lib/openfeature/sdk/provider

Flipper can be integrated with OpenFeature SDK

https://github.com/open-feature/openfeature.dev/pull/235

cc: @bkeepers @jnunemaker

**Comment by kiliczsh** [comment]
@jnunemaker OpenFeature is a standardization for feature flags. As there is no Ruby provider Flipper can be first one to support OpenFeature. If you have more specific questions may be @beeme1mr can answer them.

**Comment by bkeepers** [comment]
@kiliczsh Are you asking us to work on the implementation, or are you offering to work on it?

**Comment by bkeepers** [comment]
Closing since we never heard back. Support for OpenFeature is not a request we've had from any users or customers, so it's not a priority for us at the moment.

**Comment by n2p5** [comment]
Just FYI, much like we only consider telemetry options that integrate with OpenTelemetry, we are only considering feature flag options that are supported by OpenFeature. 

Open feature is a CNCF project now, https://www.cncf.io/projects/openfeature/ and removing third-party vendor code from our business logic is a top priority. So, while you might not have current customers asking for this, you risk losing new customers who take a standards-based approach to building cloud-native tooling.
