### ISSUE TITLE
gem 'flipper-active_record' is messing with the queue adaptor.

### ISSUE THREAD

**Issue by myxoh** [flippercloud/flipper#767]
This may be specific to our configuration but.

- We are using GoodJob as our queue adaptor
- We are using ActiveRecord as our adaptor for Flipper
- We are using rails 7

**Before:**
On our initializors we were initializing our Queue in an initialisor like:
`config/initializers/queue.rb`

```ruby
Rails.application.configure do
  config.active_job.queue_adapter = :good_job
  # ... etc
end
```

After adding the flipper gem, specifically the `flipper-active_record` - while the `queue_adapter` was still configured correctly when reading: `Rails.configuration.active_job.queue_adapter` => `:good_job`

It was now defaulting to the async adaptor when running: `ActiveJob::Base.queue_adapter` (And actually using this adaptor).

We manage to pinpoint the issue to requiring the gem which was loading it before the initializors. We fixed the issue by setting 

```ruby
gem 'flipper-active_record'  require: false
````
on the Gemfile and then requiring the gem later down the line after the queue was correctly set.

Ideally - requiring this adaptor should NOT be initializing the queue in any way and causing this kind of dependency issues

**Comment by jnunemaker** [comment]
@myxoh We use the same stack without this issue (good job, rails 7, flipper + AR). Hmm....

@bkeepers can you think of anything in the automatic configuring that could somehow affect good job?

**Comment by bkeepers** [comment]
We definitely use that stack everywhere. Here's what I just tried to duplicate the issue you're describing:

```
rails new flipper_767 --database= postgresql
cd flipper_767
bin/bundle add good_job
bin/bundle add flipper-active_record
bin/rails g good_job:install
bin/rails g flipper:active_record
bin/rails db:migrate
echo "Rails.application.configure do
  config.active_job.queue_adapter = :good_job
end
" >> config/initializers/queue.rb
```

And now when I verify:

```
$ rails/console
>> Rails.version
=> "7.1.0.rc2"
>> Rails.configuration.active_job.queue_adapter
=> :good_job
>> Flipper.adapter.adapter.class
=> Flipper::Adapters::ActiveRecord
```

That all looks right to me. Do you get the same result?


Is something else overwriting `queue_adapter` after you set it, and it just happens that it's being triggered by `flipper-actrive_record`? Can you try adding this to the top of your `queue.rb` initializer to see if anything is changing it after you do?

```
Rails.configuration.active_job.class_eval do
  def queue_adapter=(value)
    puts "Setting queue adapter to #{value.inspect}", caller.first(3)
    super
  end
end
```

**Comment by bkeepers** [comment]
@myxoh closing since we didn't hear back from you, but let us know if you're still having issues.
