### ISSUE TITLE
KeyError: key not found: true in strict mode

### ISSUE THREAD

**Issue by Linuus** [flippercloud/flipper#792]
If I use this config:

```rb
config.flipper.strict = !Rails.env.production?
# or simply
config.flipper.strict = true
```

I get this:

```rb
[1] pry(main)> Flipper.enabled?(:wat)
KeyError: key not found: true
from /Users/.../ruby/3.1.2/lib/ruby/gems/3.1.0/gems/flipper-1.1.2/lib/flipper/adapters/strict.rb:26:in `fetch'
```

Shouldn't it raise that the feature doesn't exist? This looks more like the config itself breaks.

On Flipper 1.1.2.

**Comment by jnunemaker** [comment]
@bkeepers is looking into this. Thanks for reporting!

**Comment by bkeepers** [comment]
@Linuus thanks for reporting the issue. Definitely looks like a bug. I'm working on a fix now, but in the mean time, you should be able to do this:

```ruby
config.flipper.strict = Rails.env.production? ? false : :raise
```
