### ISSUE TITLE
Inconsistency - custom description, banner_text uses `Sanitize` but actor names is fully escaped

### ISSUE THREAD

**Issue by arathunku** [flippercloud/flipper#805]
Hello!

I'm in a process of updating to v1.1 release, it's great and expressions are super useful :)

There's 1 inconsistency I've noticed when trying to make UI a bit more user friendly 

- any value for `actor_names_source` is fully escaped
- descriptions are using `<%== Sanitize.fragment(@feature.description, Sanitize::Config::BASIC) %>` - 

I found this out when I wanted to display links as values in actor names for quicker navigation. I can do that 

We can already add HTML in `banner_text` too, [here](https://github.com/flippercloud/flipper/blob/c134caea7a62b7ca83e344042a6b4285173f3921/lib/flipper/ui/views/layout.erb#L16), so it looks like only `actor_names_source` is not following the pattern.

Is PR to use `Sanitize` for actor name too welcome?

**Comment by bkeepers** [comment]
Thanks for pointing out the inconsistency. A PR would definitely be welcome!

**Comment by arathunku** [comment]
thanks @bryszard!
