### ISSUE TITLE
Feature flag not being enabled in RSpec specs on 1.2.1

### ISSUE THREAD

**Issue by norman** [flippercloud/flipper#822]
This may be a duplicate of #821, but I don't know enough about the internals of the library to say if it is.

In a spec, my code tries to enable a feature flag, but the flag does not end up enabled:

```ruby
# A helper we use in our specs
module TestUtils
  extend ActiveSupport::Concern

  def with_feature_flag(flag, value)
    old_value = Flipper.enabled?(flag)
    if value == false
      puts "disabling #{flag}"
      Flipper.disable(flag)
    else
      puts "enabling #{flag}"
      Flipper.enable(flag)
    end
    yield
  ensure
    if old_value == false
      puts "setting #{flag} back to disabled"
      Flipper.disable(flag)
    else
      puts "setting #{flag} back to enabled"
      Flipper.enable(flag)
    end
  end

  module ClassMethods
    def with_feature_flag(flag, value)
      around { |example| with_feature_flag(flag, value) { example.run } }
    end
  end
end
```

```ruby
# Excerpt of our spec
context "when the automatic_button feature flag is enabled" do
  with_feature_flag :automatic_button, true

  context "when there is a failure message" do
    before { subject.object.fulfillment.failure_code = "cancelled" }

    it "returns the red banner" do
       puts "Flag symbol enabled? #{Flipper.enabled? :automatic_button}"
      puts "Flag string enabled? #{Flipper.enabled? 'automatic_button'}"
      expect(subject.banner.to_partial_path).to eq "admin/order_banners/automatic_processing_failure"
    end

    it "returns the red banner, even if it can be processed automatically" do
      subject.object.fulfillment.can_process_automatically = true
      expect(subject.banner.to_partial_path).to eq "admin/order_banners/automatic_processing_failure"
    end
  end
end
```

On 1.2.1:
```
$ rspec spec/decorators/order_decorator_spec.rb:114
Run options: include {:locations=>{"./spec/decorators/order_decorator_spec.rb"=>[114]}}
enabling automatic_button
Flag symbol enabled? false
Flag string enabled? false
setting automatic_button back to disabled
```
On 1.1.2:
```
$ rspec spec/decorators/order_decorator_spec.rb:114
Run options: include {:locations=>{"./spec/decorators/order_decorator_spec.rb"=>[114]}}
enabling automatic_button
Flag symbol enabled? true
Flag string enabled? true
setting automatic_button back to disabled
```
In case it's helpful, this is on Rails 7.0.8 and RSpec 3.12.0.

**Comment by bkeepers** [comment]
@norman Sorry you're running into issues. `TestHelp` was just added in 1.2 and is enabled by default. I'm guessing there's an order issue with the `before`/`around` callbacks. 

To help isolate it, can you first try disabling the `TestHelp` integration?

```ruby
# config/initializers/flipper.rb
Rails.application.configure do
  config.flipper.test_help = false
end
```

If your test pass after that, then I'm guessing what is happening is:

1. Your `with_feature_flag` helper enables the feature in the `around` block
2. `TestHelp#flipper_configure` gets called, resetting the current flipper instance
3. The specs run with the newly configured flipper instance

**Comment by norman** [comment]
> Sorry you're running into issues. 

@bkeepers No worries! Thanks for the quick response and thanks for working on this library that my coworkers and I are super happy with.

> To help isolate it, can you first try disabling the TestHelp integration?

Yes, the specs pass when I add the initializer your provided.

**Comment by bkeepers** [comment]
@norman can you try [this branch](https://github.com/flippercloud/flipper/tree/rspec-prepend) with your original `with_feature_flag` helper? 

```ruby
gem 'flipper-active_record', git: 'https://github.com/flippercloud/flipper', branch: 'rspec-prepend'
```

**Comment by norman** [comment]
> @norman can you try [this branch](https://github.com/flippercloud/flipper/tree/rspec-prepend) with your original `with_feature_flag` helper?
> 
> ```ruby
> gem 'flipper-active_record', git: 'https://github.com/flippercloud/flipper', branch: 'rspec-prepend'
> ```

Yes! That worked.

**Comment by bkeepers** [comment]
> Yes! That worked.

Awesome. And just to confirm, this is with `config.flipper.test_help = true`?

**Comment by norman** [comment]
> > Yes! That worked.
> 
> Awesome. And just to confirm, this is with `config.flipper.test_help = true`?

Oh crap. Sorry, I'm doing a million things at once right now and forgot to unset that. I still had your initializer running. When I removed it the specs no longer pass with your branch, the behavior is the same as my original report.

**Comment by d-otis** [comment]
Howdy 👋🏻 🤠 
FWIW Jumping in here to say I'm experiencing a similar issue in a Rails(7.0.8) app albeit we use Redis instead of ActiveRecord for Flipper. We are using RSpec v3.12 with `Flipper.enable`/`disable` in our tests. These tests were passing before this update.

The `config` changes in the Flipper initializer mentioned earlier in this thread allowed our Flipper-related tests to pass 🤩 , but the `rspec-prepend` gem branch did not. I was guessing at the gem though: 
```
gem 'flipper-redis', git: 'https://github.com/flippercloud/flipper', branch: 'rspec-prepend'
```
I could be wrong there ☝🏻 
LMK if you have other questions 🙏🏻
