### ISSUE TITLE
How to design a request-scoped per-actor flag state table?

### ISSUE THREAD

**Issue by julik** [flippercloud/flipper#852]
In our setting we tend to use Flipper flags a lot, and sometimes - in repeat renders such as partials. I was looking at memoization but I could not figure out whether memoization takes the feature gates into account for a particular actor (i.e. in how far is the gating shifted "below" or "above" the memo).

Maybe I do not understand something, but isn't it so that the memoization will still "drop through" to the gates, even if this feature flag has already been requested for this particular actor? Thing is, I am looking for a way to save the complete FF table for a particular user at the start of a request, and wipe it off afterwards. This will allow us to amortize the gate application (and N+whatever queries with it) over the multiple renders we perform - which makes perfect sense, as it is not important for us that the flag value be "current" and be able to update during, say, a running ActiveJob or controller action.

For now I have arrived at this monstrosity, but it is gross:

```ruby
# Flipper does have memoization, but it did not seem to work when using Actors.
# We actually do want to cache per-actor (normally - per Account) since a feature flag
# might be getting addressed hundreds of times per render. Basically we need a request-scoped,
# account-scoped cache. "Just" memoization
module FlipperPerAccountMemo
  def enabled?(feature_name, *args)
    actor, *rest = *args
    return super unless actor.is_a?(Account)

    if Current.flipper_flag_state_for_current_account.nil?
      Current.flipper_flag_state_for_current_account = {}
      Flipper.features.map(&:name).each_with_object({}) do |other_feature_name|
        Current.flipper_flag_state_for_current_account[feature_name] = super(other_feature_name, *args)
      end
    end

    from_flag_state = Current.flipper_flag_state_for_current_account.fetch(feature_name, false)

    # Feature flags get switched in tests without resetting Current
    # (inside of a single test case) and we want this to keep working
    if Rails.env.test?
      super_result = super
      if from_flag_state != super_result
        Rails.logger.warn { "The value of the feature flag #{feature_name.inspect} for #{actor} was cached as #{from_flag_state} but is now #{super_result}" }
      end
      return super_result 
    end

    from_flag_state
  end
end

Flipper::DSL.prepend(FlipperPerAccountMemo)
```

but it feels as if there should be an existing piece in Flipper which helps with that, I'm just not finding it. Or would putting a cache store inside `Current` and looping it into the `Memoized` a better option? it still seems that this will have the same problem (there will be actor-related work done per call to `enabled?`)

**Comment by bkeepers** [comment]
@julik by default, Flipper will preload and memoize all gate data for the duration of each web request. So there should be only one network call to load flipper data, regardless of actor or number of times features are checked. You can read more about those optimizations here: https://www.flippercloud.io/docs/optimization

You can set `Flipper.memoize = true` in console to see it working. In the screenshot below, notice:

1. Repeated calls to `enabled?` are trigging ActiveRecord queries
2. Turned on memoization with `Flipper.memoize = true`
3. After the next `enabled?` call there are no more queries. This would be true even for different actors.

![image](https://github.com/flippercloud/flipper/assets/173/513ee498-fa6b-4378-85ac-068613f83a48)

So you shouldn't need any custom code to memoize. Let me know if I'm not understanding or you still have a question that I'm not answering.

**Comment by julik** [comment]
Oh my @bkeepers thank you. I forgot to do _one_ crucial thing - update the gems before asking. This makes so much sense. So do I understand correctly that:

* Features can be memoized, and their feature _gates_ and "actor" definitions too? Just the definitions are runnable code. But there is no memoization for the feature flag _values_ for a particular actor.
* When memoized, there won't be requests to the feature store, but the feature gates will still be applied at runtime? So when I call `enabled?` and, say, a "admin group membership" check that we have queries the DB, I will still end up with N+1 queries?

**Comment by jnunemaker** [comment]
> When memoized, there won't be requests to the feature store, but the feature gates will still be applied at runtime? So when I call enabled? and, say, a "admin group membership" check that we have queries the DB, I will still end up with N+1 queries?

Correct, any queries you have in groups will be invoked at runtime. Everything else will be preloaded. 

This is why we're hardening expressions so that groups can someday no longer be needed. With expressions you can provide properties up front however you want and then know that flag evaluation will never invoke network calls.

**Comment by julik** [comment]
Thank you gentlemen!
