### ISSUE TITLE
Stop Flipper from outputting things in the console

### ISSUE THREAD

**Issue by adrianthedev** [flippercloud/flipper#870]
I would like to stop these output lines from the console and logs.
Is there a quick way to do that?

![CleanShot 2024-06-12 at 13 57 35@2x](https://github.com/flippercloud/flipper/assets/1334409/f24bca84-ea69-43de-895d-d44ae8855a0b)

Thank you!

**Comment by bkeepers** [comment]
You can disable logging with:

```ruby
# config/initializers/flipper.rb
Rails.application.configure do
  config.flipper.log = false
end
```

**Comment by adrianthedev** [comment]
Thanks @bkeepers!
