### ISSUE TITLE
Prevent Flipper Logs when running Sidekiq

### ISSUE THREAD

**Issue by RachalCassity** [flippercloud/flipper#876]
I have `config.flipper.log = false` defined in the Flipper initializer. When running `bundle exec sidekiq`, these logs are flooding in. I do not see these logs in the rails logs, only Sidekiq logs.

<img width="1338" alt="Screenshot 2024-08-15 at 2 31 03 PM" src="https://github.com/user-attachments/assets/e3b3c460-12bb-41bc-bd0e-8e519b7ce46c">

**Comment by jnunemaker** [comment]
These are the active record queries. We only suppress the flipper logging but if active record or other adapters do logging we leave it alone. 

You definitely can suppress active record logging by increasing the log level or logging to /dev/null or something but not sure if you want to do that. 

Any other questions related to this or other flipper things?

**Comment by jnunemaker** [comment]
Let me know if there is anything else I can help with here. Happy to drop more examples or answer questions.
