### ISSUE TITLE
All feature flags return false on first page load in local and staging environments

### ISSUE THREAD

**Issue by svpersteve** [flippercloud/flipper#878]
Apologies if this is something we've done in setup but locally and in our staging environment, the first load of the page after signing in returns false for all feature flags until we refresh the page. 

For example we have a feature on our home page that's fully enabled but on first load it shows the old view and it confuses everyone for a second until you refresh.

**Comment by jnunemaker** [comment]
@svpersteve hi there! I don't have any other reports of anything like this. I'll need more info. 

Can you drop some of your flipper configs if you have any? 

Also, what version of ruby, rails and flipper gems are you using? 

What adapter are you using? 

Closing to keep things tidy but will re-open if we can confirm a bug. Happy to keep answering your questions here though.
