### ISSUE TITLE
Enable all feature flags in test & development environment by default

### ISSUE THREAD

**Issue by knagode** [flippercloud/flipper#889]
Is there an easy way in order for all flags to return true? (I need this in test & development env)

**Comment by nanto88** [comment]
this issue related to me
https://github.com/flippercloud/flipper/issues/893

the workaround is either override to enable again or patch the module
```ruby
require 'flipper/test_help'

module Flipper
  module TestHelp
    extend self

    def flipper_configure
      # Use a shared Memory adapter for all tests. This is instantiated outside of the
      # `configure` block so the same instance is returned in new threads.
      adapter = Flipper::Adapters::Memory.new

      Flipper.configure do |config|
        config.adapter { adapter }
        config.default { Flipper.new(config.adapter) }
      end
    end

    # patch flipper_reset to avoid removing all features in every run rspec (before each)
    def flipper_reset
      nil
    end
  end
end

```

**Comment by jnunemaker** [comment]
Hey sorry for slow response. Check this out: https://github.com/flippercloud/flipper/issues/482 for more info on enabling by default. 

You could also just use a setup/before block to Flipper.features.each { |feature| feature.enable } or something like that. That would only work with known features but gets the job done.
