### ISSUE TITLE
Set flipper reset to configurable in test_help.rb

### ISSUE THREAD

**Issue by nanto88** [flippercloud/flipper#893]
my project has default flipper enable for some value set once in rspec configure.
The issue is in test_help.rb:30 configure rspec.config before(:each) to reset the flipper value

can we have a configurable to disable and enable the flipper reset ?

Reference : 
flipper-1.3.1/lib/flipper/test_help.rb:30

**Comment by jnunemaker** [comment]
I'm struggling to understand why you'd want to do this. Can you explain the problem you are having or what you are trying to do? Closing to keep things tidy here but happy to keep chatting.

**Comment by nanto88** [comment]
In the large project with many rspec test cases, all of the rspec test takes an hour.
we enable several flipper features at once,
when the flipper newer version has flipper_reset in every block before each test, we need to add flipper in every block after each test instead just called once. 
its not an issue but nice to have if we can disable the flipper reset. thanks for the response

**Comment by joshgoebel** [comment]
Ping.  Also running afoul of this.  We have our own before/after that sets feature states for various groups of tests and they are being interfered with by this global each that is essentially reseting all our flags right after we have set them appropriately for the test that is about to run.

**Comment by jnunemaker** [comment]
@joshgoebel have you tried just turning the test help off? 

https://github.com/flippercloud/flipper/blob/47239f905b31e2b68b40137a21546778846e1ca5/lib/flipper/engine.rb#L29

You can set env var `FLIPPER_TEST_HELP=false` or set config.flipper.test_help = false. I think either of those will work. Give it a try and let me know.

**Comment by joshgoebel** [comment]
Yeah, I meant to circle back here and suggest the ENV variable to others.  Just turned it off works like a charm - wonder if this should be documented somewhere in upgrading guides?
