### ISSUE TITLE
No Rails 8 support

### ISSUE THREAD

**Issue by morgoth** [flippercloud/flipper#894]
Currently flipper AR gem requires version below 8 https://github.com/flippercloud/flipper/blob/main/flipper-active_record.gemspec#L35
Rails 8 was just released

**Comment by brandondrew** [comment]
It would be wonderful if there were any status updates on this issue 🙏🏼

**Comment by jnunemaker** [comment]
I’m close on main. Just some ci failures with older versions of Ruby I have
to fix. I was at rubyconf this week.

**Comment by brandondrew** [comment]
Thanks for the update! 

# 🥳 🙌🏼 👏🏻
