### ISSUE TITLE
Warning raised under Ruby 3.3.5, relating to PStore no longer being a default gem from Ruby 3.5.0

### ISSUE THREAD

**Issue by benilovj** [flippercloud/flipper#897]
We are seeing the following warning as part of our build, when running `rspec` under Ruby 3.3.5:

`.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/flipper-1.3.1/lib/flipper/adapters/pstore.rb:2: warning: /Users/benilovj/.rbenv/versions/3.3.5/lib/ruby/3.3.0/pstore.rb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add pstore to your Gemfile or gemspec to silence this warning.
Also please contact the author of flipper-1.3.2 to request adding pstore into its gemspec.`

**Comment by jnunemaker** [comment]
Thanks for reporting. Fix incoming.

**Comment by bvogel** [comment]
I see your point.

I looked into conditionally including dependencies and that seems to be a pain in the butt. How about adding `pstore` in an after install hook to the Gemfile if it's not already installed for ruby versions 3.3.x+`?
